baseURL: https://weichzh.github.io/
publishDir: docs
languageCode: zh
theme: 'PaperMod'
title: 微尘众的博客

enableRobotsTXT: true
enableEmoji: true
paginate: 10
buildDrafts: false
buildFuture: false
buildExpired: false
defaultContentLanguage: zh
hasCJKLanguage: true
disqusShortname: https-weichzh-github-io

minify:
  disableXML: true
  # minifyOutput: true

taxonomies:
  tag: tags

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: 微尘众的博客
  description: "言语道断，非去来今"
  keywords: [Blog, Technology, PaperMod, Philosophy]
  author: Weichzh
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  ShowToc: true
  TocOpen: false


  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "img/favicon.ico"
    favicon16x16: "img/favicon-16x16.png"
    favicon32x32: "img/favicon-32x32.png"
    apple_touch_icon: "img/apple-touch-icon.png"
    safari_pinned_tab: "img/favicon.ico"

  label:
    text: "主页"
    icon: "/img/apple-touch-icon.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: 微尘众
    subtitle: "言语道断，非去来今"
    imageUrl: "img/avatar.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle:
    # buttons:
    #   - name: 博文
    #     url: posts
    #   - name: 标签
    #     url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    # - name: twitter
    #   url: "https://twitter.com/"
    # - name: stackoverflow
    #   url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/weichzh"

  analytics:
    google:
      SiteVerificationTag: "G-SLEQ73N24W"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: search
      name: 搜索
      url: /search/
      weight: 10
    - identifier: tags
      name: 标签
      url: /tags/
      weight: 20
    - identifier: posts
      name: 文章
      url: posts
      weight: 30
    - identifier: archives
      name: 归档
      url: /archives/
      weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
frontmatter:
  date:
    - date
    - publishDate
    - lastmod
  lastmod:
    - :git
    - lastmod
    - date
    - publishDate
  publishDate:
    - publishDate
    - date
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: darcula
outputs:
  home:
    - HTML
    - CSS
    - JSON
